# Generated by Django 6.0.6 on 2026-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
