# Generated by Django 6.0.6 on 2026-06-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='a',
        ),
    ]
